### ISSUE TITLE
Bots became zoombie after dying

### ISSUE THREAD

**Issue by ricsal1** [PureGero/minecraft-stress-test#11]
Bots became zombie after dying and no longer trigger stress on server, giving erroneous benchmark values

**Comment by PureGero** [comment]
In the README.md:

`Note that bots are unable to respawn, we recommend giving them creative mode.`

You can delete their playerdata in between tests to respawn them

**Comment by ricsal1** [comment]
Hi m8,
I have changed it and in a way the bots don't break.
Can I sent a PR for it? Tried yesterday but it keeps giving me 403.

Thanks

**Comment by ricsal1** [comment]
![imagem](https://user-images.githubusercontent.com/25226624/232922641-a770a4d1-4384-4d20-a828-4d75f6e09d39.png)

**Comment by SnowzNZ** [comment]
You need to fork the repo then create a PR from that

**Comment by PureGero** [comment]
Should be fixed by #13
